version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/vedledle_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - vedledle_network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=vedledle_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/src/main/resources/dbinit.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vedledle_network

volumes:
  pgdata:

networks:
  vedledle_network:
