version: '3'
services:
  frontend:
    image: 011323159004.dkr.ecr.eu-north-1.amazonaws.com/vedledle-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - vedledle_network

  backend:
    image: 011323159004.dkr.ecr.eu-north-1.amazonaws.com/vedledle-backend:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://vedledle.cluster-ro-cvaygozdccix.eu-north-1.rds.amazonaws.com:5432/vedledle_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgresvedledle
    networks:
      - vedledle_network

volumes:
  pgdata:

networks:
  vedledle_network:
