spring:
  security:
    oauth2:
      authorizationserver:
        client:
          client-1:
            registration:
              client-id: "admin-client"
              client-secret: "{bcrypt}$2a$10$3TdRriHKCU0uZNC9rRsbf.cDkcQshwa5vcgl.Hs3nGlFBbYF0xFqK"
              client-authentication-methods: "client_secret_basic"
              authorization-grant-types: "client_credentials"
              scopes: "user.read,user.write"
logging:
  level:
    org.springframwork.security: "trace"

server:
  port: "9000"
