spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vedledle
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  web:
    resources:
      static-locations: classpath:/frontend/
logging:
  level:
    org.hibernate.SQL: debug
